// <auto-generated />
namespace AngularWebAPI2oauth2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Refresh : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Refresh));

        string IMigrationMetadata.Id
        {
            get { return "201505161310516_Refresh"; }
        }

        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
